In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Balaji Fast Food Sales.csv")
df

,order_id,date,item_name,item_type,item_price,quantity,transaction_amount,transaction_type,received_by,time_of_sale
0,1,07-03-2022,Aalopuri,Fastfood,20,13,260,NaN,Mr.,Night
1,2,8/23/2022,Vadapav,Fastfood,20,15,300,Cash,Mr.,Afternoon
2,3,11/20/2022,Vadapav,Fastfood,20,1,20,Cash,Mr.,Afternoon
3,4,02-03-2023,Sugarcane juice,Beverages,25,6,150,Online,Mr.,Night
4,5,10-02-2022,Sugarcane juice,Beverages,25,8,200,Online,Mr.,Evening
...,...,...,...,...,...,...,...,...,...,...
995,996,3/19/2023,Frankie,Fastfood,50,10,500,NaN,Mrs.,Evening
996,997,9/20/2022,Sandwich,Fastfood,60,7,420,NaN,Mr.,Evening
997,998,1/26/2023,Sandwich,Fastfood,60,13,780,NaN,Mr.,Evening
998,999,8/27/2022,Panipuri,Fastfood,20,5,100,NaN,Mrs.,Afternoon
999,1000,5/29/2022,Aalopuri,Fastfood,20,3,60,Online,Mrs.,Midnight

In [3]:
df.isnull().sum()

order_id                0
date                    0
item_name               0
item_type               0
item_price              0
quantity                0
transaction_amount      0
transaction_type      107
received_by             0
time_of_sale            0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            1000 non-null   int64
 1   date                1000 non-null   object
 2   item_name           1000 non-null   object
 3   item_type           1000 non-null   object
 4   item_price          1000 non-null   int64
 5   quantity            1000 non-null   int64
 6   transaction_amount  1000 non-null   int64
 7   transaction_type    893 non-null    object
 8   received_by         1000 non-null   object
 9   time_of_sale        1000 non-null   object
dtypes: int64(4), object(6)
memory usage: 78.3+ KB

In [5]:
df= pd.read_csv("Balaji Fast Food Sales.csv")
df['date']= df['date'].astype(str).str.strip()

df['date_parsed'] = np.where(
    df['date'].str.contains('/'),
    pd.to_datetime(df['date'],format= '%m/%d/%Y', errors='coerce'),
    pd.to_datetime(df['date'],format= '%d-%m-%Y',errors= 'coerce')
)

df['date'] = df['date_parsed']
df.drop(columns=['date_parsed'],inplace= True)

In [6]:
df.describe()

,order_id,date,item_price,quantity,transaction_amount
count,1000.000000,1000,1000.000000,1000.000000,1000.000000
mean,500.500000,2022-10-02 05:15:21.600000,33.315000,8.162000,275.230000
min,1.000000,2022-01-04 00:00:00,20.000000,1.000000,20.000000
25%,250.750000,2022-06-17 00:00:00,20.000000,4.000000,120.000000
50%,500.500000,2022-09-21 00:00:00,25.000000,8.000000,240.000000
75%,750.250000,2023-01-02 00:00:00,50.000000,12.000000,360.000000
max,1000.000000,2023-12-03 00:00:00,60.000000,15.000000,900.000000
std,288.819436,NaN,14.921744,4.413075,204.402979

In [7]:
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day_name()
df['year'] = df['date'].dt.year
df

,order_id,date,item_name,item_type,item_price,quantity,transaction_amount,transaction_type,received_by,time_of_sale,month,day,year
0,1,2022-03-07,Aalopuri,Fastfood,20,13,260,NaN,Mr.,Night,March,Monday,2022
1,2,2022-08-23,Vadapav,Fastfood,20,15,300,Cash,Mr.,Afternoon,August,Tuesday,2022
2,3,2022-11-20,Vadapav,Fastfood,20,1,20,Cash,Mr.,Afternoon,November,Sunday,2022
3,4,2023-03-02,Sugarcane juice,Beverages,25,6,150,Online,Mr.,Night,March,Thursday,2023
4,5,2022-02-10,Sugarcane juice,Beverages,25,8,200,Online,Mr.,Evening,February,Thursday,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-03-19,Frankie,Fastfood,50,10,500,NaN,Mrs.,Evening,March,Sunday,2023
996,997,2022-09-20,Sandwich,Fastfood,60,7,420,NaN,Mr.,Evening,September,Tuesday,2022
997,998,2023-01-26,Sandwich,Fastfood,60,13,780,NaN,Mr.,Evening,January,Thursday,2023
998,999,2022-08-27,Panipuri,Fastfood,20,5,100,NaN,Mrs.,Afternoon,August,Saturday,2022
999,1000,2022-05-29,Aalopuri,Fastfood,20,3,60,Online,Mrs.,Midnight,May,Sunday,2022

In [8]:

df.fillna({'transaction_type' : 'Unknown'}, inplace= True)

**Total Sales (KPI)**

In [9]:
total_sales = df['transaction_amount'].sum()
print("Total Sales:", total_sales)

Total Sales: 275230

**Top Selling Items**

In [10]:
item_sales= df.groupby('item_name')['transaction_amount'].sum().sort_values(ascending= False)
print(item_sales)

item_name
Sandwich           65820
Frankie            57500
Cold coffee        54440
Sugarcane juice    31950
Panipuri           24520
Aalopuri           20880
Vadapav            20120
Name: transaction_amount, dtype: int64

**Most Sold Item (Quantity)**

In [11]:
df.groupby('item_name')['quantity'].sum().sort_values(ascending= False)

item_name
Cold coffee        1361
Sugarcane juice    1278
Panipuri           1226
Frankie            1150
Sandwich           1097
Aalopuri           1044
Vadapav            1006
Name: quantity, dtype: int64

**Sales by Time of Day**

In [12]:
df.groupby('time_of_sale')['transaction_amount'].sum().sort_values(ascending= False)

time_of_sale
Night        62075
Afternoon    56345
Morning      53730
Evening      52355
Midnight     50725
Name: transaction_amount, dtype: int64

**Payment Method Analysis**

In [13]:
df.groupby('transaction_type')['transaction_amount'].sum()

transaction_type
Cash       132840
Online     110595
Unknown     31795
Name: transaction_amount, dtype: int64

In [14]:
df['month'] = df['month'].str.strip()

**Monthly sales Trend**

In [15]:
monthly_sales= df.groupby('month')['transaction_amount'].sum()
monthly_sales

month
April        21060
August       22965
December     22520
February     25520
January      25465
July         19450
June         19160
March        25120
May          26170
November     22735
October      21195
September    23870
Name: transaction_amount, dtype: int64

In [16]:
months_order = [
    'January','February','March','April','May','June','July','August','September',
    'October','November','December']

In [17]:
monthly_sales= df.groupby('month')['transaction_amount'].sum()
monthly_sales= monthly_sales.reindex(months_order)
monthly_sales

month
January      25465
February     25520
March        25120
April        21060
May          26170
June         19160
July         19450
August       22965
September    23870
October      21195
November     22735
December     22520
Name: transaction_amount, dtype: int64

In [26]:
df.groupby('month')['transaction_amount'].sum().idxmax()

'May'

In [29]:
may_sales= df[df['date'].dt.month == 5]
result = may_sales.groupby('item_name')['quantity'].sum().sort_values(ascending=False)
print(result)

item_name
Vadapav            165
Frankie            150
Aalopuri           118
Cold coffee        104
Sandwich            89
Panipuri            78
Sugarcane juice     78
Name: quantity, dtype: int64

**Item type Analysis**

In [18]:
df.groupby('item_type')['transaction_amount'].sum()

item_type
Beverages     86390
Fastfood     188840
Name: transaction_amount, dtype: int64

In [20]:
df.groupby('day')['transaction_amount'].sum().sort_values(ascending= False)

day
Monday       46100
Thursday     40655
Sunday       40235
Wednesday    39260
Saturday     38790
Tuesday      35335
Friday       34855
Name: transaction_amount, dtype: int64

In [21]:
df.groupby('item_name')['item_price'].mean().sort_values(ascending= False).head()

item_name
Sandwich           60.0
Frankie            50.0
Cold coffee        40.0
Sugarcane juice    25.0
Aalopuri           20.0
Name: item_price, dtype: float64

In [22]:
df.groupby('time_of_sale')['transaction_amount'].sum().idxmax()

'Night'

In [23]:
df.groupby(['time_of_sale', 'item_type',])['quantity'].sum().sort_values(ascending= False)

time_of_sale  item_type
Night         Fastfood     1233
Midnight      Fastfood     1135
Morning       Fastfood     1081
Afternoon     Fastfood     1052
Evening       Fastfood     1022
Afternoon     Beverages     662
Night         Beverages     526
Evening       Beverages     518
Morning       Beverages     493
Midnight      Beverages     440
Name: quantity, dtype: int64

**Project Insights**

1. Sandwich generated the highest revenue, even though Cold Coffee had higher sales volume,
   indicating a higher price per unit.

2. Sales peaked at the month of May, where Vada Pav recorder the highest sales.

3. Fast Food items were sold the most during night time.

4. Overall customer demand was highest for the Fast Food Category.